pagina = open('pagina.html', 'w', encoding='utf-8')
pagina.write('<!DOCTYPE html>\n')
pagina.write('<html lang="br">\n')
pagina.write('<head>\n')
pagina.write('<meta charset="utf-8">\n')
pagina.write('<title>Titulo da Pagina</title>\n')
pagina.write('</head>\n')
pagina.write('<body>\n')
pagina.write('Ola para o grupo Python Iniciantes!')
for l in range(100):
    pagina.write(f'<p>{l}</p>\n')
pagina.write('</body>\n')
pagina.write('</html>\n')
pagina.close()